### ISSUE TITLE
Inheritance of the graphical interface UI

### ISSUE THREAD

**Issue by Navadvipa-Chandra-das** [copperspice/cs_designer#1]
Hare Krishna, All!
Please accept my humble obeisances! All glory to Shrila Prabhupada!

The Designer utility is very useful, but since there is no GUI inheritance, it becomes useless in many cases.
In order to make such inheritance, you need to perform several steps.
1. Selecting an ancestor from already created UI
2. Step-by-step loading of widgets. First, the oldest ancestor, then the younger one loads, then the younger one, and so on until the youngest one loads the widgets.
3. Each widget should have a note - whether it is inherited or new. It is mandatory to save new widgets in an XML file, but widgets marked IsInherited should save only those properties that have changed compared to the closest ancestor! IsInherited can be a function.
4. A rule should be added that prohibits deleting widgets marked IsInherited!

Hare Krishna!
Thank You!
With best regards, Navadvipa Chandra das.

**Comment by bgeller** [comment]
Here is a quote from our CS API Documentation. 

"Designer is a stand alone program which developers can use to graphically create or edit User Interface files. The .UI files are compiled with your application to seamlessly create the visual interface your application will display. Using the Designer program is an efficient and convenient way to layout complex graphical screens which often contains numerous widgets and dialogs."

https://www.copperspice.com/docs/cs_api/tools-designer.html

The .UI file is saved using the XML format and must contain all of the information required to create the user interface for a given window.  Each GUI window in your application can either be drawn by hand or created at run time by a .UI file.  

I am not sure about the word "ancestor". This is not part of our API documentation so it is unclear what it you mean. There is no older ancestor so again, we are lost. 

Have you taken a look at some of the existing UI files in our KitchenSink demo or maybe in the Diamond program? 

Maybe you can start again and let us know what you wanted to use the Designer program for. It is not an IDE if that helps as a starting place.

Barbara

**Comment by Navadvipa-Chandra-das** [comment]
Hare Krishna, Barbara and All!
Please accept my humble obeisances!
All glory to Shila Prabhupada!
I was referring to the chain of visual inheritance, as in Embarcadero C++Builder. I almost always made forms (windows) that had the TForm base class as a distant ancestor, for example:
TForm -> TfmvRes -> TfmvDB -> TfmvRights
TForm -> TfmvRes -> TfmvDB -> TfmvRoles
TForm -> TfmvRes -> TfmvChangePassword
This is both classical inheritance of C++ classes, and also visual inheritance!
At least you can learn from the code that is generated from the ui file. But C++Builder uses its own format of dfm files, not XML format files.
I am very grateful to you for such good examples as KitchenSink and Diamond and CS_Designer. I have already looked through the code and will look again. I started writing my project "Srila Prabhupada's Dictionary" on CopperSpice, but so far it's just the beginning, it hasn't even reached compilation. Srila Prabhupada -this founder-acharya of the International Society for Krishna Consciousness is His Divine Grace Sri Srimad Abhai Charanaravinda Bhaktivedankta Swami Prabhupada!

Hare Krishna!
With best regards, Navadvipa Chandra das.

**Comment by bgeller** [comment]
We are not familiar with the other product you mentioned.  My guess is that CS Designer and Builder are not trying to solve the same issues. 

Glad you started to look at the UI forms in some of our other products. For some of the examples in KitchenSink we created the user interface by hand just to show how it can be accomplished.  You might want to open some of the KS or Diamond UI file in Designer to see how we created them.  If you have other questions please ask.

**Comment by bgeller** [comment]
> This is both classical inheritance of C++ classes, and also visual inheritance

Not sure there is a computer term of classical inheritance. A class which inherits from a parent class is simply a child class or you can call it a derived class. 

I am sure the term "visual inheritance" is correct.  The Designer program allows you to see a visual representation of the widgets and controls on the window.  Since there is no business logic in a UI file the idea of inheritance does not apply.  To see how the window is used requires looking at the source code.  

We have around 35 examples and tutorials with full explanations in our CS Journal. Full source code is available for download. These might give you some insight into using CopperSpice.  New examples are added frequently and a blog about user interface files is in the works.

https://journal.copperspice.com/

Happy to hear you are writing a program using the CS libraries.

**Comment by agserm** [comment]
Feel free to reopen this issue if you have further questions.
